export let data = [
    {
      dimension: "450 X 300",
      title: "Fancy Product",
      rating: "",
      price: "",
      disprice: "$40.00 - $80.00",
      buttonName: "View Options",
      changedname: "View Options",
    },
    {
      dimension: "450 X 300",
      title: "Special Item",
      rating: "⭐⭐⭐⭐⭐",
      price: "$20.00 ",
      disprice: "$18.00",
      buttonName: "Add to cart",
      changedname: "Remove from cart",
    },
    {
      dimension: "450 X 300",
      title: "Sale Item",
      rating: "",
      price: "$50.00 ",
      disprice: "$25.00",
      buttonName: "Add to cart",
      changedname: "Remove from cart",
    },
    {
      dimension: "450 X 300",
      title: "Popular Item",
      rating: "⭐⭐⭐⭐⭐",
      disprice: "$40.00",
      buttonName: "Add to cart",
      changedname: "Remove from cart",
    },
    {
      dimension: "450 X 300",
      title: "Sale Item",
      rating: "",
      price: "$50.00 ",
      disprice: "$25.00",
      buttonName: "Add to cart",
      changedname: "Remove from cart",
    },
    {
      dimension: "450 X 300",
      title: "Fancy Product",
      rating: "",
      price: "",
      disprice: "$40.00 - $80.00",
      buttonName: "View Options",
      changedname: "View Options",
    },
    {
      dimension: "450 X 300",
      title: "Special Item",
      rating: "⭐⭐⭐⭐⭐",
      price: "$20.00 ",
      disprice: "$18.00",
      buttonName: "Add to cart",
      changedname: "Remove from cart",
    },
    {
      dimension: "450 X 300",
      title: "Popular Item",
      rating: "⭐⭐⭐⭐⭐",
      disprice: "$40.00",
      buttonName: "Add to cart",
      changedname: "Remove from cart",
    },
  ];